# Generated by Django 4.2.2 on 2023-08-29 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_userinfo_alter_user_order_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Order',
            new_name='UserOrder',
        ),
        migrations.RenameModel(
            old_name='User_Request',
            new_name='UserRequest',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='name',
            new_name='UserName',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='password',
            new_name='pwd',
        ),
        migrations.AlterField(
            model_name='userorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userinfo'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userinfo'),
        ),
    ]
